import React = require("react");
export declare var el: typeof React.createElement;
export declare var a: (props: __TSX.aProps, ...children: any[]) => React.ReactElement<__TSX.aProps>;
export declare var article: __TSX.El;
export declare var section: __TSX.El;
export declare var aside: __TSX.El;
export declare var div: __TSX.El;
export declare var p: __TSX.El;
export declare var span: __TSX.El;
export declare var button: __TSX.El;
export declare var form: __TSX.El;
export declare var input: __TSX.El;
export declare var h1: __TSX.El;
export declare var h2: __TSX.El;
export declare var h3: __TSX.El;
export declare var h4: __TSX.El;
export declare var h5: __TSX.El;
export declare var h6: __TSX.El;
export declare var head: __TSX.El;
export declare var header: __TSX.El;
export declare var i: __TSX.El;
export declare var img: (props: __TSX.imgProps) => React.ReactElement<__TSX.imgProps>;
export declare var svg: __TSX.El;
export declare var ul: __TSX.El;
export declare var ol: __TSX.El;
export declare var li: __TSX.El;
export declare var nav: __TSX.El;
export declare var table: __TSX.El;
export declare var thead: __TSX.El;
export declare var tbody: __TSX.El;
export declare var th: __TSX.El;
export declare var tr: __TSX.El;
export declare var td: __TSX.El;
export declare var s_break: __TSX.El;
export declare var m_break: __TSX.El;
export declare var l_break: __TSX.El;
export declare var br: __TSX.El;
export declare var row: __TSX.El;
